const constants = {
  BTC_ASK_ADDED: "BTC_ASK_ADDED",
  BTC_ASK_DESTROYED: "BTC_ASK_DESTROYED",
  BTC_BID_ADDED: "BTC_BID_ADDED",
  BTC_BID_DESTROYED: "BTC_BID_DESTROYED",

  BCH_ASK_ADDED: "BCH_ASK_ADDED",
  BCH_ASK_DESTROYED: "BCH_ASK_DESTROYED",
  BCH_BID_ADDED: "BCH_BID_ADDED",
  BCH_BID_DESTROYED: "BCH_BID_DESTROYED",

  VCN_ASK_ADDED: "VCN_ASK_ADDED",
  VCN_ASK_DESTROYED: "VCN_ASK_DESTROYED",
  VCN_BID_ADDED: "VCN_BID_ADDED",
  VCN_BID_DESTROYED: "VCN_BID_DESTROYED",

}

module.exports = constants;