const constants = {
  BTC_ASK_ADDED: "BTC_ASK_ADDED",
  BTC_ASK_DESTROYED: "BTC_ASK_DESTROYED",
  BTC_BID_ADDED: "BTC_BID_ADDED",
  BTC_BID_DESTROYED: "BTC_BID_DESTROYED",

  BCH_ASK_ADDED: "BCH_ASK_ADDED",
  BCH_ASK_DESTROYED: "BCH_ASK_DESTROYED",
  BCH_BID_ADDED: "BCH_BID_ADDED",
  BCH_BID_DESTROYED: "BCH_BID_DESTROYED",

  INR_ASK_ADDED: "INR_ASK_ADDED",
  INR_ASK_DESTROYED: "INR_ASK_DESTROYED",
  INR_BID_ADDED: "INR_BID_ADDED",
  INR_BID_DESTROYED: "INR_BID_DESTROYED",

  USD_ASK_ADDED: "USD_ASK_ADDED",
  USD_ASK_DESTROYED: "USD_ASK_DESTROYED",
  USD_BID_ADDED: "USD_BID_ADDED",
  USD_BID_DESTROYED: "USD_BID_DESTROYED",

  EUR_ASK_ADDED: "EUR_ASK_ADDED",
  EUR_ASK_DESTROYED: "EUR_ASK_DESTROYED",
  EUR_BID_ADDED: "EUR_BID_ADDED",
  EUR_BID_DESTROYED: "EUR_BID_DESTROYED",

  GBP_ASK_ADDED: "GBP_ASK_ADDED",
  GBP_ASK_DESTROYED: "GBP_ASK_DESTROYED",
  GBP_BID_ADDED: "GBP_BID_ADDED",
  GBP_BID_DESTROYED: "GBP_BID_DESTROYED",

  BRL_ASK_ADDED: "BRL_ASK_ADDED",
  BRL_ASK_DESTROYED: "BRL_ASK_DESTROYED",
  BRL_BID_ADDED: "BRL_BID_ADDED",
  BRL_BID_DESTROYED: "BRL_BID_DESTROYED",

  PLN_ASK_ADDED: "PLN_ASK_ADDED",
  PLN_ASK_DESTROYED: "PLN_ASK_DESTROYED",
  PLN_BID_ADDED: "PLN_BID_ADDED",
  PLN_BID_DESTROYED: "PLN_BID_DESTROYED",

  CAD_ASK_ADDED: "CAD_ASK_ADDED",
  CAD_ASK_DESTROYED: "CAD_ASK_DESTROYED",
  CAD_BID_ADDED: "CAD_BID_ADDED",
  CAD_BID_DESTROYED: "CAD_BID_DESTROYED",

  TRY_ASK_ADDED: "TRY_ASK_ADDED",
  TRY_ASK_DESTROYED: "TRY_ASK_DESTROYED",
  TRY_BID_ADDED: "TRY_BID_ADDED",
  TRY_BID_DESTROYED: "TRY_BID_DESTROYED",

  RUB_ASK_ADDED: "RUB_ASK_ADDED",
  RUB_ASK_DESTROYED: "RUB_ASK_DESTROYED",
  RUB_BID_ADDED: "RUB_BID_ADDED",
  RUB_BID_DESTROYED: "RUB_BID_DESTROYED",

  MXN_ASK_ADDED: "MXN_ASK_ADDED",
  MXN_ASK_DESTROYED: "MXN_ASK_DESTROYED",
  MXN_BID_ADDED: "MXN_BID_ADDED",
  MXN_BID_DESTROYED: "MXN_BID_DESTROYED",

  CZK_ASK_ADDED: "CZK_ASK_ADDED",
  CZK_ASK_DESTROYED: "CZK_ASK_DESTROYED",
  CZK_BID_ADDED: "CZK_BID_ADDED",
  CZK_BID_DESTROYED: "CZK_BID_DESTROYED",

  ILS_ASK_ADDED: "ILS_ASK_ADDED",
  ILS_ASK_DESTROYED: "ILS_ASK_DESTROYED",
  ILS_BID_ADDED: "ILS_BID_ADDED",
  ILS_BID_DESTROYED: "ILS_BID_DESTROYED",

  NZD_ASK_ADDED: "NZD_ASK_ADDED",
  NZD_ASK_DESTROYED: "NZD_ASK_DESTROYED",
  NZD_BID_ADDED: "NZD_BID_ADDED",
  NZD_BID_DESTROYED: "NZD_BID_DESTROYED",

  JPY_ASK_ADDED: "JPY_ASK_ADDED",
  JPY_ASK_DESTROYED: "JPY_ASK_DESTROYED",
  JPY_BID_ADDED: "JPY_BID_ADDED",
  JPY_BID_DESTROYED: "JPY_BID_DESTROYED",

  SEK_ASK_ADDED: "SEK_ASK_ADDED",
  SEK_ASK_DESTROYED: "SEK_ASK_DESTROYED",
  SEK_BID_ADDED: "SEK_BID_ADDED",
  SEK_BID_DESTROYED: "SEK_BID_DESTROYED",

  AUD_ASK_ADDED: "AUD_ASK_ADDED",
  AUD_ASK_DESTROYED: "AUD_ASK_DESTROYED",
  AUD_BID_ADDED: "AUD_BID_ADDED",
  AUD_BID_DESTROYED: "AUD_BID_DESTROYED",

}

module.exports = constants;